### ISSUE TITLE
topLayoutGuide references in -2.WithModel and -3.UIPickerView

### ISSUE THREAD

**Issue by ezefib** [Thinkful-Ed/ObjectiveC_Uber_Unit2_UnitConverterApp#3]
Current statement on line 65 (of -2.WithModel) is causing the app to crash when you first open it. Recommend to remove the UIView definition for topLayoutGuide and change line 66 with the make.top.equalTo statement below.

[self.celsiusLabel mas_makeConstraints:^(MASConstraintMaker *make) {
//UIView *topLayoutGuide = (id)self.topLayoutGuide; // remove
//make.top.equalTo(topLayoutGuide.mas_bottom).offset(verticalSpace); //remove
make.top.equalTo(self.view.mas_top).offset(verticalSpace);
make.leading.equalTo(self.view.mas_leading).offset(leadingOffset);
make.trailing.equalTo(self.view.mas_trailing).offset(trailingOffset);
}];

Similar change for the -3.UIPickerView (line 63) recommended also.

**Comment by craiggrummitt** [comment]
Good pick-up, I've made this change to all branches. Please confirm and close issue when you're happy with the fix!
Incidentally this also impacted the [Movies repo](https://github.com/Thinkful-Ed/ObjectiveC_Uber_Unit3_MoviesApp) and [assignment 3.2.1](https://courses.thinkful.com/uber-ios-001/assignment/3.2.1). I've made changes to these as well.

**Comment by ezefib** [comment]
Thanks Craig! I appreciate the quickness to address it!!
